routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\DifteriaWebController;
use App\Http\Controllers\ExportImportController;
Route::resource('difteria', DifteriaWebController::class);
Route::resource('ExportImport', ExportImportController::class);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/create',[DifteriaWebController::class, 'create']);
// Route::delete('/{difteria}',[DifteriaWebController::class, 'destroy']);
Route::put('/update',[DifteriaWebController::class, 'update']);
Route::get('/search',[DifteriaWebController::class, 'search']);

Route::get('/export',[ExportImportController::class, 'export'])->name('export');
Route::get('/',[ExportImportController::class, 'index'])->name('index');
Route::post('/import',[ExportImportController::class, 'import'])->name('import');

app/Models/data_difteria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class data_difteria extends Model
{
    use HasFactory;

    protected $fillable = [
        'kecamatan','jml_kepadatan','jml_rumahtdksehat','jml_vaksin_dpt','jml_kasus','tahun',
    ];
}

app/Http/Controllers/DataDifteriaController.php
<?php

namespace App\Http\Controllers;
use App\models\data_difteria;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DataDifteriaController extends Controller
{
    public function index(){

        return data_difteria::all();
    }

    public function create(Request $request){
        $data=new data_difteria;
        $data->jml_kepadatan=$request->jml_kepadatan;
        $data->jml_rumahtdksehat=$request->jml_rumahtdksehat;
        $data->jml_vaksin_dpt=$request->jml_vaksin_dpt;
        $data->jml_penderita=$request->jml_penderita;
        $data->save();

        return " Data Tersimpan ";
    }

    public function update(Request $request, $id){
        $data=data_difteria::find($id);
        $data->jml_kepadatan=$request->jml_kepadatan;
        $data->jml_rumahtdksehat=$request->jml_rumahtdksehat;
        $data->jml_vaksin_dpt=$request->jml_vaksin_dpt;
        $data->jml_penderita=$request->jml_penderita;
        $data->save();

        return " Data Terupdate ";
    }

    public function delete($id){
        $data=data_difteria::find($id);
        $data->delete();

        return " Data Terhapus ";
    }

    public function detail($id){
        $data=data_difteria::find($id);

        return $data;
    }

    public function detail2016(){
        $data = data_difteria::where('tahun', 2016)->get();
        return $data;
    }

    public function rendah2016(){
        $data = data_difteria::where('tahun', 2016)->where('cluster', 'C1')->get();
        return $data;
    }

    public function sedang2016(){
        $data = data_difteria::where('tahun', 2016)->where('cluster', 'C2')->get();
        return $data;
    }

    public function tinggi2016(){
        $data = data_difteria::where('tahun', 2016)->where('cluster', 'C3')->get();
        return $data;
    }


    public function detail2017(){
        $data = data_difteria::where('tahun', 2017)->get();
        return $data;
    }


    public function rendah2017(){
        $data = data_difteria::where('tahun', 2017)->where('cluster', 'C1')->get();
        return $data;
    }

    public function sedang2017(){
        $data = data_difteria::where('tahun', 2017)->where('cluster', 'C2')->get();
        return $data;
    }

    public function tinggi2017(){
        $data = data_difteria::where('tahun', 2017)->where('cluster', 'C3')->get();
        return $data;
    }


    public function detail2018(){
        $data = data_difteria::where('tahun', 2018)->get();
        return $data;
    }
    
    public function rendah2018(){
        $data = data_difteria::where('tahun', 2018)->where('cluster', 'C1')->get();
        return $data;
    }

    public function sedang2018(){
        $data = data_difteria::where('tahun', 2018)->where('cluster', 'C2')->get();
        return $data;
    }

    public function tinggi2018(){
        $data = data_difteria::where('tahun', 2018)->where('cluster', 'C3')->get();
        return $data;
    }

    public function detail2019(){
        $data = data_difteria::where('tahun', 2019)->get();
        return $data;
    }

    
    public function rendah2019(){
        $data = data_difteria::where('tahun', 2019)->where('cluster', 'C1')->get();
        return $data;
    }

    public function sedang2019(){
        $data = data_difteria::where('tahun', 2019)->where('cluster', 'C2')->get();
        return $data;
    }

    public function tinggi2019(){
        $data = data_difteria::where('tahun', 2019)->where('cluster', 'C3')->get();
        return $data;
    }

    public function detail2020(){
        $data = data_difteria::where('tahun', 2020)->get();
        return $data;
    }

    
    public function rendah2020(){
        $data = data_difteria::where('tahun', 2020)->where('cluster', 'C1')->get();
        return $data;
    }

    public function sedang2020(){
        $data = data_difteria::where('tahun', 2020)->where('cluster', 'C2')->get();
        return $data;
    }

    public function tinggi2020(){
        $data = data_difteria::where('tahun', 2020)->where('cluster', 'C3')->get();
        return $data;
    }
}

resources/views/data_difterias/create.blade.php
@extends('template')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create New Data</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('difteria.index') }}"> Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('difteria.store') }}" method="POST">
    @csrf
 
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kecamatan</strong>
                <input type="text" name="kecamatan" class="form-control" placeholder="kecamatan">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jumlah Kepadatan</strong>
                <input type="number" name="jml_kepadatan" class="form-control" placeholder="jml_kepadatan">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jumlah Rumah Tidak Sehat</strong>
                <input type="number" name="jml_rumahtdksehat" class="form-control" placeholder="jml_rumahtdksehat">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jumlah Vaksin DPT</strong>
                <input type="number" name="jml_vaksin_dpt" class="form-control" placeholder="jml_vaksin_dpt">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jumlah Kasus Difteri</strong>
                <input type="number" name="jml_kasus" class="form-control" placeholder="jml_kasus">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tahun</strong>
                <input type="number" name="tahun" class="form-control" placeholder="tahun">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
 
</form>
@endsection

resources/views/data_difterias/edit.blade.php
@extends('template')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Edit</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-secondary" href="{{ route('difteria.index') }}"> Back</a>
            </div>
        </div>
    </div>
 
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
 
    <form action="{{ route('difteria.update',$difterium->id) }}" method="POST">
        @csrf
        @method('PUT')
 
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Kecamatan</strong>
                    <input type="text" name="kecamatan" value="{{ $difterium->kecamatan }}" class="form-control" placeholder="kecamatan">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Kepadatan</strong>
                    <input type="number" name="jml_kepadatan" value="{{ $difterium->jml_kepadatan }}" class="form-control" placeholder="jml_kepadatan">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Rumah Tidak Sehat</strong>
                    <input type="number" name="jml_rumahtdksehat" value="{{ $difterium->jml_rumahtdksehat }}" class="form-control" placeholder="jml_rumahtdksehat">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Vaksin DPT</strong>
                    <input type="number" name="jml_vaksin_dpt" value="{{ $difterium->jml_vaksin_dpt }}" class="form-control" placeholder="jml_vaksin_dpt">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Kasus Difteri</strong>
                    <input type="number" name="jml_kasus" value="{{ $difterium->jml_kasus }}" class="form-control" placeholder="jml_kasus">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Tahun</strong>
                    <input type="number" name="tahun" value="{{ $difterium->tahun }}" class="form-control" placeholder="tahun">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
 
    </form>
@endsection

resources/views/data_difterias/exim.blade.php
@extends('template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2> Export Import Data Difteria</h2>
        </div>
        <div class="float-lg-right" style="margin-right: 5px;">
            <a class="btn btn-secondary" href="{{ route('difteria.index') }}"> Back</a>
        </div>
        <div class="float-lg-right" style="margin-right: 5px;">
            <a class="btn btn-success" href="{{ route('export') }}">Export</a>
        </div>
        <div class="float-lg-right" style="margin-right: 5px;">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Import</a>
        </div>

    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<div class="card card-info card-outline">
    <div class="card-body">
        <table class="table table-bordered">
            <tr class="text-center">
                <th>Kecamatan</th>
                <th>Kepadatan</th>
                <th>Rumah Tidak Sehat</th>
                <th>Vaksin DPT</th>
                <th>Kasus Difteri</th>
                <th>Tahun</th>
            </tr>
            @foreach ($exim as $post)
            <tr class="text-center">
                <td>{{ $post->kecamatan }}</td>
                <td>{{ $post->jml_kepadatan }}</td>
                <td>{{ $post->jml_rumahtdksehat }}</td>
                <td>{{ $post->jml_vaksin_dpt }}</td>
                <td>{{ $post->jml_kasus }}</td>
                <td>{{ $post->tahun }}</td>
            </tr>
            @endforeach
        </table>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Import Data</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('import') }}" method="post" enctype="multipart/form-data">
                    <div class="modal-body">

                        {{ csrf_field() }}
                        <div class="form-group">
                            <input type="file" name="file" required="required">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Import</button>
                    </div>
            </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
@endsection

resources/views/data_difterias/index.blade.php
@extends('template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2> Web Admin Difteria</h2>
        </div>
        <div class="col-md-4">
            <form action="/search" method="get">
                <div class="input-group">
                    <input type="search" name="search" class="form-control" style="margin-right: 10px;">
                    <span class="input-group-prepend">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </span>
                </div>
            </form>
        </div>
        <div class="float-right">
            <a class="btn btn-success" href="{{ route('difteria.create') }}"> Create</a>
        </div>
        <div class="float-lg-right" style="margin-right: 5px;">
            <a class="btn btn-success" href="{{ route('ExportImport.index') }}"> Export Import</a>
        </div>
        <div class="float-lg-right" style="margin-right: 5px;">
            <a class="btn btn-secondary" href="{{ route('difteria.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <tr class="text-center">
        <th>Kecamatan</th>
        <th>Kepadatan</th>
        <th>Rumah Tidak Sehat</th>
        <th>Vaksin DPT</th>
        <th>Kasus Difteri</th>
        <th>Tahun</th>
        <th width="280px" class="text-center">Action</th>
    </tr>
    @foreach ($posts as $post)
    <tr class="text-center">
        <td>{{ $post->kecamatan }}</td>
        <td>{{ $post->jml_kepadatan }}</td>
        <td>{{ $post->jml_rumahtdksehat }}</td>
        <td>{{ $post->jml_vaksin_dpt }}</td>
        <td>{{ $post->jml_kasus }}</td>
        <td>{{ $post->tahun }}</td>

        <td class="text-center">
            <form action="{{ route('difteria.destroy',$post->id) }}" method="POST">

                <a class="btn btn-primary btn-sm" href="{{ route('difteria.edit',$post->id) }}">Update</a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $posts->links('pagination::bootstrap-4') !!}

@endsection

resources/views/data_difterias/show.blade.php
@extends('template')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2> Show Post</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-secondary" href="{{ route('data_difteria.index') }}"> Back</a>
            </div>
        </div>
    </div>
 
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong></strong>
                {{ $post->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $post->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $post->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $post->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $post->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Content:</strong>
                {{ $post->content }}
            </div>
        </div>
    </div>
@endsection